// Code generated by "stringer -type=Format"; DO NOT EDIT.

package picam

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[YUV-0]
	_ = x[RGB-1]
	_ = x[Gray-2]
}

const _Format_name = "YUVRGBGray"

var _Format_index = [...]uint8{0, 3, 6, 10}

func (i Format) String() string {
	if i >= Format(len(_Format_index)-1) {
		return "Format(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Format_name[_Format_index[i]:_Format_index[i+1]]
}
